// Path: Assets\Scripts\Editor\LiteNetworkedObjectCreator.cs
// This file is automatically generated by LiteNetworkedObjectCreator.cs and SHOULD NOT BE EDITED MANUALLY.
using UnityEngine;
using UnityEditor;
using Pnak;

namespace PnakEditor
{
	public class LiteNetworkedSO : ScriptableObject
	{
		private static LiteNetworkedSO instance;
		public static LiteNetworkedSO Instance
		{
			get
			{
				if (instance == null)
				{
					instance = CreateInstance<LiteNetworkedSO>();
					instance.hideFlags = HideFlags.DontSave;
				}
				return instance;
			}
		}

		private static SerializedObject serializedInstance;
		public static SerializedObject SerializedInstance
		{
			get
			{
				if (serializedInstance == null)
				{
					serializedInstance = new SerializedObject(Instance);
				}
				return serializedInstance;
			}
		}

		public LiteNetworkedData.HealthVisualData HealthVisualDataField;
		public LiteNetworkedData.KinematicPositionData KinematicPositionDataField;
		public LiteNetworkedData.LifetimeData LifetimeDataField;
		public LiteNetworkedData.PositionAndChildRotationData PositionAndChildRotationDataField;
		public LiteNetworkedData.ReloadVisualData ReloadVisualDataField;
		public LiteNetworkedData.StaticTransformData StaticTransformDataField;
	}
}
